name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  windows:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner:
          - windows-2022
          - windows-2025
        arch:
          - x64
          - x86
          - amd64_arm64
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive
      - uses: TheMrMilchmann/setup-msvc-dev@v4
        with:
          arch: ${{ matrix.arch }}
      - name: Build
        shell: cmd
        run: |
          cmake -GNinja -B build .
          cmake --build build --target all
      - name: Test
        if: ${{ matrix.arch != 'amd64_arm64' }}
        shell: cmd
        run: |
          .\build\egif_demo.exe

  macos:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner:
          - macos-15
          - macos-26
          - macos-15-intel
          - macos-26-intel
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive
      - name: Build
        run: |
          cmake -GNinja -B build .
          cmake --build build --target all
      - name: Test
        run: |
          ./build/egif_demo

  linux:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner:
          - ubuntu-22.04
          - ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive
      - name: Build
        run: |
          cmake -GNinja -B build .
          cmake --build build --target all
      - name: Test
        run: |
          ./build/egif_demo
